export { default as NavBar } from './NavBar'
export { default as NavBar2 } from './NavBar2'
export { default as Homepage } from './Homepage'
export { default as Exchanges } from './Exchanges'
export { default as Cryptocurrencies } from './Cryptocurrencies'
export { default as CryptoDetails} from './CryptoDetails'
export { default as Stocks } from './Stocks'
export { default as NASDAQ } from './NASDAQ'
export { default as NYSE2 } from './NYSE2'
export { default as NYSE } from './NYSE'
export { default as LSE } from './LSE'
export { default as LSE2 } from './LSE2'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Root } from './Root'
export { default as Favourites } from './Favourites'
export { default as HighChange } from './HighChange'
export {default as LowChange} from './LowChange'
export {default as StockDetails } from './StockDetails'
export { default as StockDetails2 } from './StockDetails2'
export { default as User } from './User'
export { default as Comments } from './Comments'
export { default as MostPopular } from './MostPopular'
export { default as CryptoNews } from './CryptoNews'
export { default as StockNews } from './StockNews'
export { default as SidePanelNews } from './SidePanelNews'
export { default as Chart } from './Chart'

